# Generated by Django 3.2.25 on 2025-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='city',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='title',
        ),
        migrations.AddField(
            model_name='travelschedule',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
