# Generated by Django 5.1.5 on 2025-02-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_images'),
        ),
    ]
