# Generated by Django 3.2.25 on 2025-02-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250215_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=36.5),
        ),
    ]
