# Generated by Django 3.2.25 on 2025-02-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashzzim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashrequest',
            name='flash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_requests', to='flash.flash'),
        ),
        migrations.AddField(
            model_name='flashrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashparticipants',
            name='flash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_participants', to='flash.flash'),
        ),
        migrations.AddField(
            model_name='flashparticipants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flash',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='flashzzim',
            unique_together={('user', 'flash')},
        ),
        migrations.AlterUniqueTogether(
            name='flashrequest',
            unique_together={('flash', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='flashparticipants',
            unique_together={('flash', 'user')},
        ),
    ]
