# Generated by Django 5.1.5 on 2025-02-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_alter_flash_latitude_alter_flash_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flash',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, null=True),
        ),
    ]
