# Generated by Django 5.1.5 on 2025-02-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_alter_flash_latitude_alter_flash_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flash',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
