# Generated by Django 5.1.5 on 2025-02-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_alter_flash_latitude_alter_flash_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
