# Generated by Django 3.2.25 on 2025-02-12 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('판매', '🛒 판매해요'), ('구매', '🛍️ 구매해요'), ('나눔', '🎁 나눔해요')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('의약품', '#의약품'), ('티켓', '#티켓'), ('음식', '#음식'), ('생활용품', '#생활용품'), ('기념품', '#기념품'), ('기타', '#기타')], max_length=10)),
                ('explanation', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_unit', models.CharField(choices=[('₩', '₩'), ('$', '$'), ('€', '€')], max_length=10)),
                ('status', models.CharField(choices=[('거래 가능', '거래 가능'), ('거래 완료', '거래 완료'), ('예약', '예약')], default='거래 가능', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='market/%Y%m%d', verbose_name='마켓_이미지')),
            ],
        ),
        migrations.CreateModel(
            name='MarketZzim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
    ]
