# Generated by Django 5.1.5 on 2025-02-02 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("판매", "🛒 판매해요"), ("구매", "🛍️ 구매해요"), ("나눔", "🎁 나눔해요")],
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("의약품", "의약품"),
                            ("티켓", "티켓"),
                            ("음식", "음식"),
                            ("생활용품", "생활용품"),
                            ("기념품", "기념품"),
                            ("기타", "기타"),
                        ],
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("거래 가능", "거래 가능"), ("거래 완료", "거래 완료"), ("예약", "예약")],
                        default="거래 가능",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
