# Generated by Django 5.1.5 on 2025-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="market/%Y%m%d", verbose_name="마켓_이미지"
            ),
        ),
    ]
