# Generated by Django 5.1.5 on 2025-02-07 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_market_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketzzim",
            name="created_at",
        ),
    ]
