# Generated by Django 5.1.5 on 2025-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_remove_marketzzim_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="currency_unit",
            field=models.CharField(
                choices=[("원", "₩"), ("달러", "$"), ("유로", "€")],
                default="원",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
