# Generated by Django 5.1.5 on 2025-02-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_alter_market_currency_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="currency_unit",
            field=models.CharField(
                choices=[("₩", "₩"), ("$", "$"), ("€", "€")], max_length=10
            ),
        ),
    ]
