# Generated by Django 3.2.25 on 2025-02-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('deleted_at_user1', models.DateTimeField(blank=True, null=True)),
                ('deleted_at_user2', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_message_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
