# Generated by Django 5.1.5 on 2025-02-06 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('accommodation_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accommodation_reviews/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
