# Generated by Django 5.1.5 on 2025-02-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationreview',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
