# Generated by Django 5.1.5 on 2025-02-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodationreview_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationreview',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationreview',
            name='location_view',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_views/'),
        ),
        migrations.AddField(
            model_name='accommodationreview',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
