# Generated by Django 3.2.25 on 2025-02-12 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0004_accommodationreview_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationreview',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
