# Generated by Django 3.2.25 on 2025-02-12 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0005_accommodationreview_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
