# Generated by Django 3.2.25 on 2025-02-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelparticipants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_travels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accompanyrequest',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='accompany.travelgroup'),
        ),
        migrations.AddField(
            model_name='accompanyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accompany_zzim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzim_items', to='accompany.travelgroup'),
        ),
        migrations.AddField(
            model_name='accompany_zzim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accompany_zzim',
            unique_together={('user', 'item')},
        ),
    ]
