# Generated by Django 5.1.5 on 2025-02-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_participant',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='travel_participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Travel_Group',
        ),
        migrations.DeleteModel(
            name='Travel_Participant',
        ),
    ]
