# Generated by Django 5.1.5 on 2025-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0002_rename_travel_participant_travelparticipants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelgroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/travel_photos/'),
        ),
    ]
