# Generated by Django 5.1.5 on 2025-02-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0002_travelgroup_now_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='markers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='polyline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
