# Generated by Django 5.1.5 on 2025-02-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accompany", "0002_accompanyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelgroup",
            name="gender",
            field=models.CharField(
                choices=[("상관없음", "상관없음"), ("남성만", "남성만"), ("여성만", "여성만")],
                default="상관없음",
                max_length=10,
            ),
        ),
    ]
