# Generated by Django 3.2.25 on 2025-02-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0006_alter_travelgroup_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='call_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
