# Generated by Django 3.2.25 on 2025-02-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_travelschedule_photo'),
        ('accompany', '0007_travelgroup_call_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='this_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_groups', to='users.travelplan'),
        ),
    ]
