# Generated by Django 3.2.25 on 2025-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0008_travelgroup_this_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelgroup',
            name='this_plan',
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='this_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
