# Generated by Django 3.2.25 on 2025-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0009_auto_20250210_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelgroup',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelgroup',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
